apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: modmanager
  namespace: workspaces
spec:
  displayName: Modmanager
  description: Modmanager is a centralised tool for downloading and updating docker
    mods for all your other Linuxserver containers.
  category: Docker
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/modmanager-logo.png
  baseImage: lscr.io/linuxserver/modmanager:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - modmanager
  - docker
