apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: qemu-static
  namespace: workspaces
spec:
  displayName: Qemu-Static
  description: Run multiple architectures of Docker containers on an x86_64 or aarch64
    host using QEMU static.
  category: Docker
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/qemu-static-logo.png
  baseImage: lscr.io/linuxserver/qemu-static:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - qemu-static
  - docker
