apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: socket-proxy
  namespace: workspaces
spec:
  displayName: Socket-Proxy
  description: The Socket Proxy is a security-enhanced proxy which allows you to apply
    access rules to the Docker socket, limiting the attack surface for containers
    such as watchtower or Traefik that need to use it.
  category: Docker
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/socket-proxy-logo.png
  baseImage: lscr.io/linuxserver/socket-proxy:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - socket-proxy
  - docker
